set exrc
set nu
set relativenumber
set nohlsearch
set hidden
set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set nowrap
"set noswapfile
set incsearch
set termguicolors
set scrolloff=10
set colorcolumn=80
set signcolumn=yes
set cmdheight=2
set mouse=a
